# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: credit_transfer_contract.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import aelf_sdk.types_pb2 as types__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='credit_transfer_contract.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1e\x63redit_transfer_contract.proto\x1a\x0btypes.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"i\n\nCourseInfo\x12\x10\n\x08\x63ourseID\x18\x01 \x01(\t\x12\x14\n\x0cisCompulsory\x18\x02 \x01(\x08\x12\x12\n\ncourseType\x18\x03 \x01(\x04\x12\x0e\n\x06\x63redit\x18\x04 \x01(\x04\x12\x0f\n\x07isValid\x18\x05 \x01(\x08\"\x89\x01\n\x0c\x43ourseRecord\x12\x10\n\x08\x63ourseID\x18\x01 \x01(\t\x12\x11\n\tstudentID\x18\x02 \x01(\t\x12\x1b\n\x08protocol\x18\x03 \x01(\x0b\x32\t.Protocol\x12\r\n\x05state\x18\x04 \x01(\x08\x12\x0b\n\x03GPA\x18\x05 \x01(\x04\x12\r\n\x05score\x18\x06 \x01(\x04\x12\x0c\n\x04note\x18\x07 \x01(\t\"\x1b\n\x08Protocol\x12\x0f\n\x07protoID\x18\x01 \x01(\t\"7\n\x03SRT\x12\x11\n\tstudentID\x18\x01 \x01(\t\x12\x0e\n\x06rating\x18\x02 \x01(\x04\x12\r\n\x05state\x18\x03 \x01(\x04\"K\n\x06School\x12\x10\n\x08schoolID\x18\x01 \x01(\t\x12\x1f\n\rschoolAddress\x18\x02 \x01(\x0b\x32\x08.Address\x12\x0e\n\x06rating\x18\x03 \x01(\x04\">\n\x07Teacher\x12 \n\x0eteacherAddress\x18\x01 \x01(\x0b\x32\x08.Address\x12\x11\n\tteacherID\x18\x02 \x01(\t\"_\n\rSRUploadInput\x12\x11\n\tstudentID\x18\x01 \x01(\t\x12\x10\n\x08\x63ourseID\x18\x02 \x01(\t\x12\x1b\n\x08protocol\x18\x03 \x01(\x0b\x32\t.Protocol\x12\x0c\n\x04note\x18\x04 \x01(\t\"2\n\x0bSRDropInput\x12\x11\n\tstudentID\x18\x01 \x01(\t\x12\x10\n\x08\x63ourseID\x18\x02 \x01(\t\"_\n\rSRModifyInput\x12\x11\n\tstudentID\x18\x01 \x01(\t\x12\x10\n\x08\x63ourseID\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\x08\x12\x0b\n\x03GPA\x18\x04 \x01(\x04\x12\r\n\x05score\x18\x05 \x01(\x04\x62\x06proto3'
  ,
  dependencies=[types__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_COURSEINFO = _descriptor.Descriptor(
  name='CourseInfo',
  full_name='CourseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='courseID', full_name='CourseInfo.courseID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isCompulsory', full_name='CourseInfo.isCompulsory', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='courseType', full_name='CourseInfo.courseType', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='credit', full_name='CourseInfo.credit', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isValid', full_name='CourseInfo.isValid', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=213,
)


_COURSERECORD = _descriptor.Descriptor(
  name='CourseRecord',
  full_name='CourseRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='courseID', full_name='CourseRecord.courseID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='studentID', full_name='CourseRecord.studentID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='CourseRecord.protocol', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='CourseRecord.state', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GPA', full_name='CourseRecord.GPA', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='CourseRecord.score', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='note', full_name='CourseRecord.note', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=353,
)


_PROTOCOL = _descriptor.Descriptor(
  name='Protocol',
  full_name='Protocol',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protoID', full_name='Protocol.protoID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=382,
)


_SRT = _descriptor.Descriptor(
  name='SRT',
  full_name='SRT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='studentID', full_name='SRT.studentID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating', full_name='SRT.rating', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='SRT.state', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=439,
)


_SCHOOL = _descriptor.Descriptor(
  name='School',
  full_name='School',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='schoolID', full_name='School.schoolID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schoolAddress', full_name='School.schoolAddress', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating', full_name='School.rating', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=516,
)


_TEACHER = _descriptor.Descriptor(
  name='Teacher',
  full_name='Teacher',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='teacherAddress', full_name='Teacher.teacherAddress', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='teacherID', full_name='Teacher.teacherID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=518,
  serialized_end=580,
)


_SRUPLOADINPUT = _descriptor.Descriptor(
  name='SRUploadInput',
  full_name='SRUploadInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='studentID', full_name='SRUploadInput.studentID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='courseID', full_name='SRUploadInput.courseID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='SRUploadInput.protocol', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='note', full_name='SRUploadInput.note', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=582,
  serialized_end=677,
)


_SRDROPINPUT = _descriptor.Descriptor(
  name='SRDropInput',
  full_name='SRDropInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='studentID', full_name='SRDropInput.studentID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='courseID', full_name='SRDropInput.courseID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=679,
  serialized_end=729,
)


_SRMODIFYINPUT = _descriptor.Descriptor(
  name='SRModifyInput',
  full_name='SRModifyInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='studentID', full_name='SRModifyInput.studentID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='courseID', full_name='SRModifyInput.courseID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='SRModifyInput.state', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GPA', full_name='SRModifyInput.GPA', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='SRModifyInput.score', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=731,
  serialized_end=826,
)

_COURSERECORD.fields_by_name['protocol'].message_type = _PROTOCOL
_SCHOOL.fields_by_name['schoolAddress'].message_type = types__pb2._ADDRESS
_TEACHER.fields_by_name['teacherAddress'].message_type = types__pb2._ADDRESS
_SRUPLOADINPUT.fields_by_name['protocol'].message_type = _PROTOCOL
DESCRIPTOR.message_types_by_name['CourseInfo'] = _COURSEINFO
DESCRIPTOR.message_types_by_name['CourseRecord'] = _COURSERECORD
DESCRIPTOR.message_types_by_name['Protocol'] = _PROTOCOL
DESCRIPTOR.message_types_by_name['SRT'] = _SRT
DESCRIPTOR.message_types_by_name['School'] = _SCHOOL
DESCRIPTOR.message_types_by_name['Teacher'] = _TEACHER
DESCRIPTOR.message_types_by_name['SRUploadInput'] = _SRUPLOADINPUT
DESCRIPTOR.message_types_by_name['SRDropInput'] = _SRDROPINPUT
DESCRIPTOR.message_types_by_name['SRModifyInput'] = _SRMODIFYINPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CourseInfo = _reflection.GeneratedProtocolMessageType('CourseInfo', (_message.Message,), {
  'DESCRIPTOR' : _COURSEINFO,
  '__module__' : 'credit_transfer_contract_pb2'
  # @@protoc_insertion_point(class_scope:CourseInfo)
  })
_sym_db.RegisterMessage(CourseInfo)

CourseRecord = _reflection.GeneratedProtocolMessageType('CourseRecord', (_message.Message,), {
  'DESCRIPTOR' : _COURSERECORD,
  '__module__' : 'credit_transfer_contract_pb2'
  # @@protoc_insertion_point(class_scope:CourseRecord)
  })
_sym_db.RegisterMessage(CourseRecord)

Protocol = _reflection.GeneratedProtocolMessageType('Protocol', (_message.Message,), {
  'DESCRIPTOR' : _PROTOCOL,
  '__module__' : 'credit_transfer_contract_pb2'
  # @@protoc_insertion_point(class_scope:Protocol)
  })
_sym_db.RegisterMessage(Protocol)

SRT = _reflection.GeneratedProtocolMessageType('SRT', (_message.Message,), {
  'DESCRIPTOR' : _SRT,
  '__module__' : 'credit_transfer_contract_pb2'
  # @@protoc_insertion_point(class_scope:SRT)
  })
_sym_db.RegisterMessage(SRT)

School = _reflection.GeneratedProtocolMessageType('School', (_message.Message,), {
  'DESCRIPTOR' : _SCHOOL,
  '__module__' : 'credit_transfer_contract_pb2'
  # @@protoc_insertion_point(class_scope:School)
  })
_sym_db.RegisterMessage(School)

Teacher = _reflection.GeneratedProtocolMessageType('Teacher', (_message.Message,), {
  'DESCRIPTOR' : _TEACHER,
  '__module__' : 'credit_transfer_contract_pb2'
  # @@protoc_insertion_point(class_scope:Teacher)
  })
_sym_db.RegisterMessage(Teacher)

SRUploadInput = _reflection.GeneratedProtocolMessageType('SRUploadInput', (_message.Message,), {
  'DESCRIPTOR' : _SRUPLOADINPUT,
  '__module__' : 'credit_transfer_contract_pb2'
  # @@protoc_insertion_point(class_scope:SRUploadInput)
  })
_sym_db.RegisterMessage(SRUploadInput)

SRDropInput = _reflection.GeneratedProtocolMessageType('SRDropInput', (_message.Message,), {
  'DESCRIPTOR' : _SRDROPINPUT,
  '__module__' : 'credit_transfer_contract_pb2'
  # @@protoc_insertion_point(class_scope:SRDropInput)
  })
_sym_db.RegisterMessage(SRDropInput)

SRModifyInput = _reflection.GeneratedProtocolMessageType('SRModifyInput', (_message.Message,), {
  'DESCRIPTOR' : _SRMODIFYINPUT,
  '__module__' : 'credit_transfer_contract_pb2'
  # @@protoc_insertion_point(class_scope:SRModifyInput)
  })
_sym_db.RegisterMessage(SRModifyInput)


# @@protoc_insertion_point(module_scope)
